### ISSUE TITLE
Close Command

### ISSUE THREAD

**Issue by AidanW4328** [ghostdevv/djs-ticketsystem#6] opened 2021-02-06 09:49 UTC
When I run ?close nothing happens but if I take away the isTicket code it closes any help? Also can you send me a dm on discord Aidan The Sister#2342 I cant dm you unless im your friend and it would just make things easier thanks in advance.

**Comment by ghostdevv** [comment] 2021-02-06 23:11
Hiya,
Is your channel topic modified in any way? The current version of djs-ticketsystem relies on a unmodified channel topic as it stores data there

If you want help via Discord you can message me or preferably join the [discord](https://discord.gg/2Vd4wAjJnm) but since you opened a issue we can deal with it here

**Comment by AidanW4328** [comment] 2021-02-07 20:35
client.on('message', message => {
    if (message.content == 'close' && message.channel.isTicket()) {
        console.log('Closed a ticket channel!')
        message.channel.delete()
    }
})

**Comment by ghostdevv** [comment] 2021-02-09 09:25
@AidanW4328 I haven't been able to reproduce this issue, are you sure you are trying to close it in a ticket channel? Is the command definitely being ran?

**Comment by AidanW4328** [comment] 2021-02-13 03:46
Yes

**Comment by ghostdevv** [comment] 2021-02-18 01:36
Will respond to you directly for ease, still not able to debug this

**Closed as completed by ghostdevv** 2021-02-18 01:36 UTC
Labels: question
